#!/usr/bin/env bash

mkdir -p static/fonts

if [ ! -d "static/fonts/DepartureMono-1.500" ]; then
  wget https://github.com/rektdeckard/departure-mono/releases/download/v1.500/DepartureMono-1.500.zip

  unzip DepartureMono-1.500.zip -d static/fonts

  rm DepartureMono-1.500.zip
fi

gcc src/*.c -o site

if [ $? -eq 0 ]; then
  chmod +x site

  ./site content
fi
