#!/bin/bash

cat build/blog/index.html | htmlq -a id h2 | while read -r line; do
  TITLE=$(cat build/blog/index.html | htmlq -t "#$line")
  DATE=$(cat build/blog/index.html | htmlq -t "#$line + p")
  DESCRIPTION=$(cat build/blog/index.html | htmlq -t "#$line + p + p")
  SLUG=$(cat build/blog/index.html | htmlq -a href "#$line + p + p + p a")
  CONTENT=$(cat "build/$SLUG.html" | htmlq main) # TODO: remove main tags
done
