#!/usr/bin/env bash
pkill -f http-server 2>/dev/null || true

sleep 1

npx http-server -c-1 build &

HTTP_PID=$!

cleanup() {
    kill $HTTP_PID
}

trap cleanup SIGINT SIGTERM

TEMP_FILES=$(mktemp)

find content >> $TEMP_FILES

find static >> $TEMP_FILES

cat $TEMP_FILES | entr scripts/generate
