#!/usr/bin/env bash

gcc src/*.c -o site

if [ $? -eq 0 ]; then
  chmod +x site

  ./site test
fi

assert() {
  if [[ "$3" != $(cat $1 | htmlq $2 --text) ]]; then
    echo "Failed to assert '$2'"
    exit 1
  fi
}

assert build/index.html '#static-site-generator' 'Static Site Generator'
assert build/index.html '#static-site-generator + p' 'A static site generator written in C.'
assert build/index.html 'h2' 'Usage'
assert build/index.html 'code' 'scripts/generate'
assert build/index.html 'h3' 'Strong Test'
assert build/index.html 'strong' 'This is strong content'
assert build/nested/test1.html 'h1' 'Neseted Test'
assert build/nested/test1.html 'p' 'This is a test file for nested content creation.'
